type = "checkout_ui_extension"
name = "po-box-validator"

extension_points = [
  'Checkout::DeliveryAddress::RenderBefore'
]

[capabilities]
block_progress = true

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"
